# Generated by Django 4.2.4 on 2023-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('email_field', models.EmailField(max_length=254)),
                ('to_field', models.EmailField(max_length=254)),
                ('comments', models.TextField(default=None)),
            ],
        ),
    ]
