# Generated by Django 4.2.4 on 2023-08-19 07:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_sharepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.expressions.Case, to='blogs.post'),
            preserve_default=False,
        ),
    ]
